dist: trusty

os:
  - linux
  - osx

language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
  - 'stable'

before_install:
  - git clone -q https://github.com/mkrufky/libdvbtee.git
  - cd libdvbtee
  - rm -rf libdvbpsi
  - git clone -q https://github.com/mkrufky/libdvbpsi.git
  - cd libdvbpsi
  - touch .dont_del
  - npm install mkdirp nan symlink-or-copy

install:
  - npm install

script:
  - npm test
