dist: trusty

language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
  - 'stable'

env:
  - CXX=g++-4.8

before_install:
  - npm install nan bindings

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8
    - gcc-4.8
