dist: trusty

os:
  - linux
  - osx

language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
  - 'stable'

before_install:
  - npm install nan

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8
    - gcc-4.8
